on: push
name: Check Assignment
jobs:  
  check-renders:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sta523-fa22/sta523-base:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Missing Packages
      run: |
        missing = checklist::install_missing_pkgs(dir = "./", glob = "hw1.qmd")
        if(length(checklist::missing_pkgs(dir='./', glob='hw1.qmd'))){
            if(!require("BiocManager", quietly = TRUE)) install.packages("BiocManager")
            missing = c(missing, checklist::install_missing_pkgs(dir = "./", glob = "hw1.qmd", repos = BiocManager::repositories()))
        }
      shell: Rscript {0}
    - name: Check Renders
      run: |
        checklist::check_qmd_renders("hw1.qmd")
      shell: Rscript {0}
    - name: Create artifacts
      uses: actions/upload-artifact@v3
      with:
        name: hw1-html
        path: hw1.html